spring.datasource.url=jdbc:mysql://localhost:3306/bright_sparks
spring.datasource.username=root
spring.datasource.password=Rishav@2005

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rishavyadav87421@gmail.com
spring.mail.password=rbhhgglfxtuyqwwf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
